# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\PyLearn\BpyQt\d190524_addOne5\zLib\fcom\fcom.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fcom(object):
    def setupUi(self, Fcom):
        Fcom.setObjectName("Fcom")
        Fcom.resize(410, 851)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Fcom.sizePolicy().hasHeightForWidth())
        Fcom.setSizePolicy(sizePolicy)
        Fcom.setMinimumSize(QtCore.QSize(400, 0))
        Fcom.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(Fcom)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_main = QtWidgets.QVBoxLayout()
        self.verticalLayout_main.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_main.setSpacing(10)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.serial_send = QtWidgets.QLineEdit(Fcom)
        self.serial_send.setMinimumSize(QtCore.QSize(200, 0))
        self.serial_send.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.serial_send.setClearButtonEnabled(True)
        self.serial_send.setObjectName("serial_send")
        self.verticalLayout_main.addWidget(self.serial_send)
        self.frame_9 = QtWidgets.QFrame(Fcom)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 45))
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.frame_9.setFont(font)
        self.frame_9.setStyleSheet("background-color: rgb(208, 241, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_8.setSpacing(1)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.serial_DataBits = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_DataBits.sizePolicy().hasHeightForWidth())
        self.serial_DataBits.setSizePolicy(sizePolicy)
        self.serial_DataBits.setMinimumSize(QtCore.QSize(40, 0))
        self.serial_DataBits.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.serial_DataBits.setFont(font)
        self.serial_DataBits.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.serial_DataBits.setObjectName("serial_DataBits")
        self.serial_DataBits.addItem("")
        self.serial_DataBits.addItem("")
        self.serial_DataBits.addItem("")
        self.serial_DataBits.addItem("")
        self.gridLayout_8.addWidget(self.serial_DataBits, 1, 6, 1, 1)
        self.serial_PortName = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_PortName.sizePolicy().hasHeightForWidth())
        self.serial_PortName.setSizePolicy(sizePolicy)
        self.serial_PortName.setMinimumSize(QtCore.QSize(60, 0))
        self.serial_PortName.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.serial_PortName.setFont(font)
        self.serial_PortName.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.serial_PortName.setObjectName("serial_PortName")
        self.serial_PortName.addItem("")
        self.gridLayout_8.addWidget(self.serial_PortName, 1, 3, 1, 1)
        self.pushButton_open = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_open.sizePolicy().hasHeightForWidth())
        self.pushButton_open.setSizePolicy(sizePolicy)
        self.pushButton_open.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_open.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_open.setFont(font)
        self.pushButton_open.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_open.setObjectName("pushButton_open")
        self.gridLayout_8.addWidget(self.pushButton_open, 0, 2, 2, 1)
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(40, 0))
        self.label_10.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_8.addWidget(self.label_10, 0, 6, 1, 1)
        self.serial_Parity = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_Parity.sizePolicy().hasHeightForWidth())
        self.serial_Parity.setSizePolicy(sizePolicy)
        self.serial_Parity.setMinimumSize(QtCore.QSize(40, 0))
        self.serial_Parity.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.serial_Parity.setFont(font)
        self.serial_Parity.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.serial_Parity.setObjectName("serial_Parity")
        self.serial_Parity.addItem("")
        self.serial_Parity.addItem("")
        self.serial_Parity.addItem("")
        self.serial_Parity.addItem("")
        self.serial_Parity.addItem("")
        self.gridLayout_8.addWidget(self.serial_Parity, 1, 8, 1, 1)
        self.pushButton_com_num = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_com_num.sizePolicy().hasHeightForWidth())
        self.pushButton_com_num.setSizePolicy(sizePolicy)
        self.pushButton_com_num.setMinimumSize(QtCore.QSize(40, 15))
        self.pushButton_com_num.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_com_num.setFont(font)
        self.pushButton_com_num.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_com_num.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_com_num.setCheckable(False)
        self.pushButton_com_num.setAutoRepeat(False)
        self.pushButton_com_num.setAutoDefault(False)
        self.pushButton_com_num.setObjectName("pushButton_com_num")
        self.gridLayout_8.addWidget(self.pushButton_com_num, 0, 3, 1, 1)
        self.serial_StopBits = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_StopBits.sizePolicy().hasHeightForWidth())
        self.serial_StopBits.setSizePolicy(sizePolicy)
        self.serial_StopBits.setMinimumSize(QtCore.QSize(40, 0))
        self.serial_StopBits.setMaximumSize(QtCore.QSize(40, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.serial_StopBits.setFont(font)
        self.serial_StopBits.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.serial_StopBits.setObjectName("serial_StopBits")
        self.serial_StopBits.addItem("")
        self.serial_StopBits.addItem("")
        self.serial_StopBits.addItem("")
        self.gridLayout_8.addWidget(self.serial_StopBits, 1, 7, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(40, 0))
        self.label_8.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_8.addWidget(self.label_8, 0, 5, 1, 1)
        self.serial_BaudRate = QtWidgets.QComboBox(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_BaudRate.sizePolicy().hasHeightForWidth())
        self.serial_BaudRate.setSizePolicy(sizePolicy)
        self.serial_BaudRate.setMinimumSize(QtCore.QSize(60, 0))
        self.serial_BaudRate.setMaximumSize(QtCore.QSize(60, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.serial_BaudRate.setFont(font)
        self.serial_BaudRate.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.serial_BaudRate.setObjectName("serial_BaudRate")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.serial_BaudRate.addItem("")
        self.gridLayout_8.addWidget(self.serial_BaudRate, 1, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setMinimumSize(QtCore.QSize(40, 0))
        self.label_12.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_8.addWidget(self.label_12, 0, 7, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(40, 0))
        self.label_11.setMaximumSize(QtCore.QSize(50, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_8.addWidget(self.label_11, 0, 8, 1, 1)
        self.pushButton_save = QtWidgets.QPushButton(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_save.sizePolicy().hasHeightForWidth())
        self.pushButton_save.setSizePolicy(sizePolicy)
        self.pushButton_save.setMinimumSize(QtCore.QSize(40, 15))
        self.pushButton_save.setMaximumSize(QtCore.QSize(60, 100))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_save.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_save.setCheckable(False)
        self.pushButton_save.setAutoRepeat(False)
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName("pushButton_save")
        self.gridLayout_8.addWidget(self.pushButton_save, 0, 10, 2, 1)
        self.verticalLayout_main.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(Fcom)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_10.setFont(font)
        self.frame_10.setStyleSheet("background-color: rgb(208, 241, 255);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout.setContentsMargins(1, 1, 1, 1)
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.check_hide = QtWidgets.QCheckBox(self.frame_10)
        self.check_hide.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_hide.sizePolicy().hasHeightForWidth())
        self.check_hide.setSizePolicy(sizePolicy)
        self.check_hide.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.check_hide.setFont(font)
        self.check_hide.setCheckable(True)
        self.check_hide.setChecked(True)
        self.check_hide.setTristate(False)
        self.check_hide.setObjectName("check_hide")
        self.gridLayout.addWidget(self.check_hide, 1, 2, 1, 1)
        self.check_new_line = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_new_line.sizePolicy().hasHeightForWidth())
        self.check_new_line.setSizePolicy(sizePolicy)
        self.check_new_line.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.check_new_line.setFont(font)
        self.check_new_line.setObjectName("check_new_line")
        self.gridLayout.addWidget(self.check_new_line, 0, 2, 1, 1)
        self.check_show_hex = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_show_hex.sizePolicy().hasHeightForWidth())
        self.check_show_hex.setSizePolicy(sizePolicy)
        self.check_show_hex.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.check_show_hex.setFont(font)
        self.check_show_hex.setObjectName("check_show_hex")
        self.gridLayout.addWidget(self.check_show_hex, 1, 1, 1, 1)
        self.pushButton_send = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send.sizePolicy().hasHeightForWidth())
        self.pushButton_send.setSizePolicy(sizePolicy)
        self.pushButton_send.setMinimumSize(QtCore.QSize(40, 20))
        self.pushButton_send.setMaximumSize(QtCore.QSize(1000, 100))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_send.setFont(font)
        self.pushButton_send.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_send.setObjectName("pushButton_send")
        self.gridLayout.addWidget(self.pushButton_send, 0, 0, 3, 1)
        self.label_sen_count = QtWidgets.QLabel(self.frame_10)
        self.label_sen_count.setMinimumSize(QtCore.QSize(70, 10))
        self.label_sen_count.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_sen_count.setFont(font)
        self.label_sen_count.setObjectName("label_sen_count")
        self.gridLayout.addWidget(self.label_sen_count, 0, 3, 1, 1)
        self.check_hex_send = QtWidgets.QCheckBox(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_hex_send.sizePolicy().hasHeightForWidth())
        self.check_hex_send.setSizePolicy(sizePolicy)
        self.check_hex_send.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.check_hex_send.setFont(font)
        self.check_hex_send.setAutoFillBackground(False)
        self.check_hex_send.setChecked(True)
        self.check_hex_send.setObjectName("check_hex_send")
        self.gridLayout.addWidget(self.check_hex_send, 0, 1, 1, 1)
        self.label_rec_count = QtWidgets.QLabel(self.frame_10)
        self.label_rec_count.setMinimumSize(QtCore.QSize(70, 10))
        self.label_rec_count.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_rec_count.setFont(font)
        self.label_rec_count.setObjectName("label_rec_count")
        self.gridLayout.addWidget(self.label_rec_count, 1, 3, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(40, 15))
        self.pushButton_clear.setMaximumSize(QtCore.QSize(60, 100))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_clear.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_clear.setCheckable(False)
        self.pushButton_clear.setAutoRepeat(False)
        self.pushButton_clear.setAutoDefault(False)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 5, 3, 1)
        self.pushButton_load = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_load.sizePolicy().hasHeightForWidth())
        self.pushButton_load.setSizePolicy(sizePolicy)
        self.pushButton_load.setMinimumSize(QtCore.QSize(40, 15))
        self.pushButton_load.setMaximumSize(QtCore.QSize(60, 100))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_load.setFont(font)
        self.pushButton_load.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_load.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_load.setCheckable(False)
        self.pushButton_load.setAutoRepeat(False)
        self.pushButton_load.setAutoDefault(False)
        self.pushButton_load.setObjectName("pushButton_load")
        self.gridLayout.addWidget(self.pushButton_load, 0, 4, 3, 1)
        self.verticalLayout_main.addWidget(self.frame_10)
        self.frame_3 = QtWidgets.QFrame(Fcom)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 255, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 255, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 255, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 255, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 255, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 255, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_3.setPalette(palette)
        self.frame_3.setAutoFillBackground(True)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_send3 = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send3.sizePolicy().hasHeightForWidth())
        self.pushButton_send3.setSizePolicy(sizePolicy)
        self.pushButton_send3.setMinimumSize(QtCore.QSize(45, 0))
        self.pushButton_send3.setMaximumSize(QtCore.QSize(45, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_send3.setFont(font)
        self.pushButton_send3.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_send3.setObjectName("pushButton_send3")
        self.horizontalLayout_3.addWidget(self.pushButton_send3)
        self.serial_send3 = QtWidgets.QLineEdit(self.frame_3)
        self.serial_send3.setMinimumSize(QtCore.QSize(0, 0))
        self.serial_send3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.serial_send3.setClearButtonEnabled(False)
        self.serial_send3.setObjectName("serial_send3")
        self.horizontalLayout_3.addWidget(self.serial_send3)
        self.check_timeSend3 = QtWidgets.QCheckBox(self.frame_3)
        self.check_timeSend3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_timeSend3.sizePolicy().hasHeightForWidth())
        self.check_timeSend3.setSizePolicy(sizePolicy)
        self.check_timeSend3.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.check_timeSend3.setFont(font)
        self.check_timeSend3.setCheckable(True)
        self.check_timeSend3.setChecked(False)
        self.check_timeSend3.setTristate(False)
        self.check_timeSend3.setObjectName("check_timeSend3")
        self.horizontalLayout_3.addWidget(self.check_timeSend3)
        self.spinBox_timeSend3 = QtWidgets.QSpinBox(self.frame_3)
        self.spinBox_timeSend3.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_timeSend3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_timeSend3.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_timeSend3.setMinimum(100)
        self.spinBox_timeSend3.setMaximum(1000000)
        self.spinBox_timeSend3.setProperty("value", 1000)
        self.spinBox_timeSend3.setObjectName("spinBox_timeSend3")
        self.horizontalLayout_3.addWidget(self.spinBox_timeSend3)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.verticalLayout_main.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(Fcom)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 255, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 255, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 255, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 255, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(213, 255, 223))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(149, 255, 175))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(56, 170, 84))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 127, 63))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 255, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.frame_2.setPalette(palette)
        self.frame_2.setAutoFillBackground(True)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_send2 = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_send2.sizePolicy().hasHeightForWidth())
        self.pushButton_send2.setSizePolicy(sizePolicy)
        self.pushButton_send2.setMinimumSize(QtCore.QSize(45, 0))
        self.pushButton_send2.setMaximumSize(QtCore.QSize(45, 21))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.pushButton_send2.setFont(font)
        self.pushButton_send2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.pushButton_send2.setObjectName("pushButton_send2")
        self.horizontalLayout.addWidget(self.pushButton_send2)
        self.serial_send2 = QtWidgets.QLineEdit(self.frame_2)
        self.serial_send2.setMinimumSize(QtCore.QSize(0, 0))
        self.serial_send2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.serial_send2.setClearButtonEnabled(False)
        self.serial_send2.setObjectName("serial_send2")
        self.horizontalLayout.addWidget(self.serial_send2)
        self.check_timeSend2 = QtWidgets.QCheckBox(self.frame_2)
        self.check_timeSend2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.check_timeSend2.sizePolicy().hasHeightForWidth())
        self.check_timeSend2.setSizePolicy(sizePolicy)
        self.check_timeSend2.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setPointSize(8)
        self.check_timeSend2.setFont(font)
        self.check_timeSend2.setCheckable(True)
        self.check_timeSend2.setChecked(False)
        self.check_timeSend2.setTristate(False)
        self.check_timeSend2.setObjectName("check_timeSend2")
        self.horizontalLayout.addWidget(self.check_timeSend2)
        self.spinBox_timeSend2 = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox_timeSend2.setMinimumSize(QtCore.QSize(80, 0))
        self.spinBox_timeSend2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.spinBox_timeSend2.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_timeSend2.setMinimum(100)
        self.spinBox_timeSend2.setMaximum(1000000)
        self.spinBox_timeSend2.setProperty("value", 1000)
        self.spinBox_timeSend2.setObjectName("spinBox_timeSend2")
        self.horizontalLayout.addWidget(self.spinBox_timeSend2)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setMaximumSize(QtCore.QSize(20, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_main.addWidget(self.frame_2)
        self.verticalLayout.addLayout(self.verticalLayout_main)

        self.retranslateUi(Fcom)
        self.serial_DataBits.setCurrentIndex(0)
        self.serial_PortName.setCurrentIndex(0)
        self.serial_BaudRate.setCurrentIndex(7)
        QtCore.QMetaObject.connectSlotsByName(Fcom)

    def retranslateUi(self, Fcom):
        _translate = QtCore.QCoreApplication.translate
        Fcom.setWindowTitle(_translate("Fcom", "COM"))
        self.serial_send.setText(_translate("Fcom", "aa 00 03 01 00 01 05 55  "))
        self.serial_DataBits.setItemText(0, _translate("Fcom", "5"))
        self.serial_DataBits.setItemText(1, _translate("Fcom", "6"))
        self.serial_DataBits.setItemText(2, _translate("Fcom", "7"))
        self.serial_DataBits.setItemText(3, _translate("Fcom", "8"))
        self.serial_PortName.setItemText(0, _translate("Fcom", "COM8"))
        self.pushButton_open.setText(_translate("Fcom", "打开"))
        self.label_10.setText(_translate("Fcom", "数据位"))
        self.serial_Parity.setItemText(0, _translate("Fcom", "N"))
        self.serial_Parity.setItemText(1, _translate("Fcom", "E"))
        self.serial_Parity.setItemText(2, _translate("Fcom", "O"))
        self.serial_Parity.setItemText(3, _translate("Fcom", "M"))
        self.serial_Parity.setItemText(4, _translate("Fcom", "S"))
        self.pushButton_com_num.setText(_translate("Fcom", "串口号"))
        self.serial_StopBits.setItemText(0, _translate("Fcom", "1"))
        self.serial_StopBits.setItemText(1, _translate("Fcom", "1.5"))
        self.serial_StopBits.setItemText(2, _translate("Fcom", "2"))
        self.label_8.setText(_translate("Fcom", "波特率"))
        self.serial_BaudRate.setItemText(0, _translate("Fcom", "1200"))
        self.serial_BaudRate.setItemText(1, _translate("Fcom", "2400"))
        self.serial_BaudRate.setItemText(2, _translate("Fcom", "4800"))
        self.serial_BaudRate.setItemText(3, _translate("Fcom", "9600"))
        self.serial_BaudRate.setItemText(4, _translate("Fcom", "19200"))
        self.serial_BaudRate.setItemText(5, _translate("Fcom", "38400"))
        self.serial_BaudRate.setItemText(6, _translate("Fcom", "57600"))
        self.serial_BaudRate.setItemText(7, _translate("Fcom", "115200"))
        self.label_12.setText(_translate("Fcom", "停止位"))
        self.label_11.setText(_translate("Fcom", "校验位"))
        self.pushButton_save.setText(_translate("Fcom", "导出\n"
"窗口"))
        self.check_hide.setText(_translate("Fcom", "隐藏扩展"))
        self.check_new_line.setText(_translate("Fcom", "发送新行"))
        self.check_show_hex.setText(_translate("Fcom", "HEX显示"))
        self.pushButton_send.setText(_translate("Fcom", "发送"))
        self.label_sen_count.setText(_translate("Fcom", "发送"))
        self.check_hex_send.setText(_translate("Fcom", "HEX发送"))
        self.label_rec_count.setText(_translate("Fcom", "接收"))
        self.pushButton_clear.setText(_translate("Fcom", "清除\n"
"窗口"))
        self.pushButton_load.setToolTip(_translate("Fcom", "<html><head/><body><p>这个按钮可以将导出的数据再次导入，并且触发QTcan2同等的效果显示</p></body></html>"))
        self.pushButton_load.setText(_translate("Fcom", "导入\n"
"窗口"))
        self.pushButton_send3.setText(_translate("Fcom", "发送3"))
        self.serial_send3.setText(_translate("Fcom", "42"))
        self.check_timeSend3.setText(_translate("Fcom", "定时发送"))
        self.label_3.setText(_translate("Fcom", "ms"))
        self.pushButton_send2.setText(_translate("Fcom", "发送2"))
        self.serial_send2.setText(_translate("Fcom", "44"))
        self.check_timeSend2.setText(_translate("Fcom", "定时发送"))
        self.label.setText(_translate("Fcom", "ms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Fcom = QtWidgets.QWidget()
    ui = Ui_Fcom()
    ui.setupUi(Fcom)
    Fcom.show()
    sys.exit(app.exec_())

